-- ─────────────────────────────────────────────────────────
--  AI Tutor — Corrected Supabase Schema
--  Auth: Username + Password (no Supabase Auth / no email)
--  Run this entire file in your Supabase SQL editor
-- ─────────────────────────────────────────────────────────

-- Users table — standalone, does NOT reference auth.users
create table if not exists public.users (
    id            text primary key,           -- UUID generated by app
    username      text unique not null,        -- login handle (lowercase)
    password_hash text not null,              -- SHA-256 hex digest
    name          text,                       -- display name
    created_at    timestamptz default now()
);

-- Chat history per user/topic
create table if not exists public.chat_history (
    id          bigserial primary key,
    user_id     text not null references public.users(id) on delete cascade,
    topic       text not null,
    role        text not null check (role in ('user', 'assistant')),
    content     text not null,
    created_at  timestamptz default now()
);

-- Topic/subtopic learning progress - CORRECTED SCHEMA
create table if not exists public.topic_progress (
    id              bigserial primary key,
    user_id         text not null references public.users(id) on delete cascade,
    course_id       text not null,           -- Course identifier (e.g., 'python_basics')
    module_idx      integer not null,        -- Module index within course
    topic_idx       integer not null,        -- Topic index within module
    status          text not null default 'not_started'
                        check (status in ('not_started', 'in_progress', 'completed')),
    score           numeric,                  -- Optional score for completed topics
    completed_at    timestamptz,             -- When topic was completed
    updated_at      timestamptz default now(), -- Last update timestamp
    unique (user_id, course_id, module_idx, topic_idx)
);

-- MCQ quiz attempts
create table if not exists public.mcq_attempts (
    id              bigserial primary key,
    user_id         text not null references public.users(id) on delete cascade,
    topic           text not null,
    question        text not null,
    selected_answer text,
    correct_answer  text not null,
    is_correct      boolean not null,
    attempted_at    timestamptz default now()
);

-- Coding task attempts
create table if not exists public.code_attempts (
    id                  bigserial primary key,
    user_id             text not null references public.users(id) on delete cascade,
    topic               text not null,
    task_description    text,
    submitted_code      text,
    test_passed         boolean not null default false,
    feedback            text,
    score               integer,              -- Score for coding attempts
    attempted_at        timestamptz default now()
);

-- ─── Indexes ─────────────────────────────────────────────
create index if not exists idx_chat_user_topic    on public.chat_history (user_id, topic);
create index if not exists idx_progress_user      on public.topic_progress (user_id);
create index if not exists idx_progress_course    on public.topic_progress (course_id);
create index if not exists idx_mcq_user           on public.mcq_attempts (user_id);
create index if not exists idx_code_user          on public.code_attempts (user_id);

-- ─── Row Level Security ───────────────────────────────────
-- Since we manage auth ourselves (no Supabase Auth JWT),
-- we disable RLS and rely on the service-level anon key +
-- app-level filtering (always query with .eq("user_id", uid)).
-- For production, use a backend API + service role key instead.
alter table public.users           disable row level security;
alter table public.chat_history    disable row level security;
alter table public.topic_progress  disable row level security;
alter table public.mcq_attempts    disable row level security;
alter table public.code_attempts   disable row level security;